name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategey:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable
            deps: sudo apt-get update ; sudo apt install libgmp-dev
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: ${{ matrix.deps }}
      - name: Test
        run: |
          cargo test --target ${{ matrix.target }}

