name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
            deps: sudo apt-get update ; sudo apt install libgmp-dev
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: ${{ matrix.deps }}
      - name: Test
        run: |
          cargo test -Z namespaced-features --all-features --target ${{ matrix.target }}

